/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "FindSimilarProfilesGithubQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "FindSimilarProfilesLinkedinQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WhopApplications": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
