export const NextEnv = {
  DB_URL: process.env.DB_URL!,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY!,
  PINECONE_API_KEY: process.env.PINECONE_API_KEY!,
  MODE: process.env.MODE!,
  COOKD_API_KEY: process.env.COOKD_API_KEY!,
  COOKD_RESUME_SCREENER_ID: process.env.COOKD_RESUME_SCREENER_ID!,
  COOKD_SLUG_ID: process.env.COOKD_SLUG_ID!,
  GITHUB_TOKEN: process.env.GITHUB_TOKEN!,
  SCRAPIN_API_KEY: process.env.SCRAPIN_API_KEY!,
  WHOP_API_KEY: process.env.WHOP_API_KEY!,
  WHOP_COOKIE: process.env.WHOP_COOKIE!,
  GITHUB_QUEUE_URL: process.env.GITHUB_QUEUE_URL!,
  LINKEDIN_QUEUE_URL: process.env.LINKEDIN_QUEUE_URL!,
  WHOP_APP_ID: process.env.WHOP_APP_ID!,
  NEXT_PUBLIC_WHOP_APP_ID: process.env.NEXT_PUBLIC_WHOP_APP_ID!,
  TOKEN_GITHUB: process.env.TOKEN_GITHUB!,
};

export const SubscriberEnv = {
  DB_URL: process.env.DB_URL!,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY!,
  PINECONE_API_KEY: process.env.PINECONE_API_KEY!,
  MODE: process.env.MODE!,
  COOKD_API_KEY: process.env.COOKD_API_KEY!,
  COOKD_RESUME_SCREENER_ID: process.env.COOKD_RESUME_SCREENER_ID!,
  COOKD_SLUG_ID: process.env.COOKD_SLUG_ID!,
  GITHUB_TOKEN: process.env.GITHUB_TOKEN!,
  SCRAPIN_API_KEY: process.env.SCRAPIN_API_KEY!,
  WHOP_API_KEY: process.env.WHOP_API_KEY!,
  WHOP_COOKIE: process.env.WHOP_COOKIE!,
  GITHUB_QUEUE_URL: process.env.GITHUB_QUEUE_URL!,
  LINKEDIN_QUEUE_URL: process.env.LINKEDIN_QUEUE_URL!,
  WHOP_APP_ID: process.env.WHOP_APP_ID!,
  NEXT_PUBLIC_WHOP_APP_ID: process.env.NEXT_PUBLIC_WHOP_APP_ID!,
  TOKEN_GITHUB: process.env.TOKEN_GITHUB!,
};
